### ISSUE TITLE
 Colorbar set_clim doesn't affect tick labels

### ISSUE THREAD

**Issue by nathanielatom** [jakevdp/mpld3#293] opened 2015-05-27 16:49 UTC
The tick labels remain between 0 and 1, no matter how the clim is set:

```python
import numpy as np
import scipy.signal as sig
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import mpld3
%matplotlib inline

# changing this determines whether the colourbar ticklabels are correctly rendered
# mpld3.disable_notebook() 
mpld3.enable_notebook()

def plot_spectrogram(t, f, l, clabel="Level [dB]", **plot_options):
    if l.shape[0] == t.size and l.shape[1] == f.size:
        l = l.transpose()
    elif l.shape[0] == f.size and l.shape[1] == t.size:
        pass
    else:
        raise ValueError("the dimensions of l (%s) must match t (%s) and f (%s)" % (l.shape, t.shape, f.shape))
    im = plt.imshow(l, interpolation='nearest', origin='lower', extent=(t[0], t[-1], f[0], f[-1]), aspect='auto',
                    **plot_options)
    vmin = plot_options.get("vmin", None)
    vmax = plot_options.get("vmax", None)
    cb = plt.colorbar()
    cb.set_label(clabel)
    cb.set_clim(vmin=vmin, vmax=vmax)

fs = 8000
chirp = sig.chirp(np.linspace(0, 30, fs * 30), 0.1, 25, 2000, method='logarithmic')
Pxx, f, t = mlab.specgram(chirp, Fs=fs)
plot_spectrogram(t, f, 20*np.log10(Pxx), clabel="Level [dB ref 1 V] [-300, 0] but the labels are incorrect", vmin=-300, vmax=0)
_ = plt.xlabel("Time [s]")
_ = plt.ylabel("Frequency [Hz]")
plt.show()
```

**Comment by jakevdp** [comment] 2015-05-28 17:04
Closing as a duplicate of #247

**Closed by jakevdp** 2015-05-28 17:04 UTC

**Comment by aflaxman** [comment] 2015-05-29 05:31
This should be fixed in the latest version from GitHub.

**Comment by nathanielatom** [comment] 2015-06-02 23:36
Thanks! Sorry, I missed the duplicate, I should have looked harder. Also, this is a really awesome library!
